force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/L_neas_de_factura__c/L_neas_de_factura__c.object-meta.xml
<CustomObject>
    <label>Líneas de factura</label>
    <nameField>
        <displayFormat>LF-{0000}</displayFormat>
        <label>Nombre de Líneas de factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de factura</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_neas_de_factura__c/fields/Descripci_n_del_producto__c.field-meta.xml
<CustomField>
    <fullName>Descripci_n_del_producto__c</fullName>
    <label>Descripción (del producto)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <label>Factura</label>
    <referenceTo>Factura__c</referenceTo>
    <relationshipLabel>Líneas de factura</relationshipLabel>
    <relationshipName>L_neas_de_factura</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <formula>Cantidad__c*Precio_unitario__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Importe_sin_impuestos__c.field-meta.xml
<CustomField>
    <fullName>Importe_sin_impuestos__c</fullName>
    <formula>Importe__c / (1 +  Valores_timpuesto__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe sin impuestos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Impuesto_texto__c.field-meta.xml
<CustomField>
    <fullName>Impuesto_texto__c</fullName>
    <formula>IF( ISPICKVAL( Tipo_de_impuesto__c , &quot;zero&quot;) , &quot;IVA 0%&quot;, IF( ISPICKVAL( Tipo_de_impuesto__c , &quot;superreduit&quot;) , &quot;IVA 4%&quot;, IF( ISPICKVAL( Tipo_de_impuesto__c , &quot;reduit&quot;) , &quot;IVA 10%&quot;, IF( ISPICKVAL( Tipo_de_impuesto__c , &quot;standard&quot;) , &quot;IVA 21%&quot;, &quot; &quot;))) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Impuesto texto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Impuestos__c.field-meta.xml
<CustomField>
    <fullName>Impuestos__c</fullName>
    <formula>Valores_timpuesto__c * Importe_sin_impuestos__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Impuestos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Lloc_de_trobada__c.field-meta.xml
<CustomField>
    <fullName>Lloc_de_trobada__c</fullName>
    <formula>IF( ISBLANK( Observaciones_del_producto__c) , false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lloc de trobada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Nombre_alternativo__c.field-meta.xml
<CustomField>
    <fullName>Nombre_alternativo__c</fullName>
    <inlineHelpText>Nombre del producto que viene de oportunidades</inlineHelpText>
    <label>Nombre alternativo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Observaciones_del_producto__c.field-meta.xml
<CustomField>
    <fullName>Observaciones_del_producto__c</fullName>
    <label>Observaciones del producto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Precio_unitario__c.field-meta.xml
<CustomField>
    <fullName>Precio_unitario__c</fullName>
    <label>Precio unitario</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Precio_unitario_sin_impuestos__c.field-meta.xml
<CustomField>
    <fullName>Precio_unitario_sin_impuestos__c</fullName>
    <formula>Importe_sin_impuestos__c  /  Cantidad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio unitario sin impuestos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Líneas de factura</relationshipLabel>
    <relationshipName>L_neas_de_factura</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Tipo_de_impuesto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_impuesto__c</fullName>
    <label>Tipo de impuesto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>zero</fullName>
                <label>0% Tasa Cero</label>
            </value>
            <value>
                <fullName>superreduit</fullName>
                <label>4% Tasa super reducida</label>
            </value>
            <value>
                <fullName>reduit</fullName>
                <label>10% Tasa baja</label>
            </value>
            <value>
                <fullName>standard</fullName>
                <label>21% Estándar</label>
            </value>
            <value>
                <fullName>none</fullName>
                <label>Exenta</label>
            </value>
            <value>
                <fullName>No aplicar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Tipo_de_producto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_producto__c</fullName>
    <formula>TEXT( Producto__r.Tipo_de_producto__c)</formula>
    <label>Tipo de producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/fields/Valores_timpuesto__c.field-meta.xml
<CustomField>
    <fullName>Valores_timpuesto__c</fullName>
    <formula>IF(ISPICKVAL ( Tipo_de_impuesto__c , &quot;zero&quot; ), 0.0,

IF(ISPICKVAL ( Tipo_de_impuesto__c , &quot;superreduit&quot; ), 0.04 ,

IF(ISPICKVAL ( Tipo_de_impuesto__c , &quot;reduit&quot; ), 0.10,

IF(ISPICKVAL( Tipo_de_impuesto__c , &quot;standard&quot; ), 0.21, 0))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valores Tipos de impuesto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExtensionFacturaPDF.cls
public class ExtensionFacturaPDF {
	   
    public List<L_neas_de_factura__c> lineasfactura{get; set;}
    
    public List<L_neas_de_factura__c> lineaslloc{get; set;}
    
	private ApexPages.StandardController stdCtrl;
    
    private Factura__c factura; 
    
    public ExtensionFacturaPDF(ApexPages.StandardController ctr){
        this.stdCtrl = ctr;
		this.factura = (Factura__c)this.stdCtrl.getRecord();
        this.lineasfactura = [SELECT Impuesto_texto__c,Lloc_de_trobada__c,Observaciones_del_producto__c,Producto__r.Name, Producto__r.Reuni_n_Previa__c, Producto__r.Datos_de_encuentros__c , Producto__r.Fecha_de_inicio__c,Producto__r.Fecha_de_fin__c,Precio_unitario_sin_impuestos__c, Cantidad__c, Descripci_n_del_producto__c, Factura__c, Importe__c, Importe_sin_impuestos__c, Impuestos__c, Name, Precio_unitario__c, Producto__c, Tipo_de_impuesto__c, Tipo_de_producto__c, Valores_timpuesto__c, Nombre_alternativo__c FROM L_neas_de_factura__c WHERE Factura__c=:factura.id];

		this.lineaslloc = [SELECT Impuesto_texto__c,Lloc_de_trobada__c,Observaciones_del_producto__c,Producto__r.Name,Precio_unitario_sin_impuestos__c, Cantidad__c, Descripci_n_del_producto__c, Factura__c, Importe__c, Importe_sin_impuestos__c, Impuestos__c, Name, Precio_unitario__c, Producto__c, Tipo_de_impuesto__c, Tipo_de_producto__c, Valores_timpuesto__c FROM L_neas_de_factura__c WHERE Factura__c=:factura.id AND Lloc_de_trobada__c=TRUE LIMIT 1];

    }
    

}