force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_emisi_n_factura__c.field-meta.xml
<CustomField>
    <fullName>Fecha_emisi_n_factura__c</fullName>
    <label>Fecha emisión factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fin_periodo_facturaci_n__c.field-meta.xml
<CustomField>
    <fullName>Fin_periodo_facturaci_n__c</fullName>
    <label>Fin periodo facturación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <inlineHelpText>Iban del CEC para las transferencias</inlineHelpText>
    <label>IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Id_de_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Id_de_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Id_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Id_de_Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Importe_total_factura__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_factura__c</fullName>
    <label>Importe total factura</label>
    <summarizedField>L_neas_de_factura__c.Importe__c</summarizedField>
    <summaryForeignKey>L_neas_de_factura__c.Factura__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/N_mero_de_factura__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_factura__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <label>Número de factura</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A (anulaciones)</fullName>
            </value>
            <value>
                <fullName>M (productos)</fullName>
            </value>
            <value>
                <fullName>SO (socios)</fullName>
            </value>
            <value>
                <fullName>SU (subscriptores)</fullName>
            </value>
            <value>
                <fullName>T (salidas)</fullName>
            </value>
            <value>
                <fullName>WE (compra web)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_Factura__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Factura__c</fullName>
    <label>Tipo de Factura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Definitiva</fullName>
            </value>
            <value>
                <fullName>Rectificativa</fullName>
            </value>
            <value>
                <fullName>Proforma</fullName>
                <isActive>false</isActive>
                <label>Proforma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pago__c</fullName>
    <label>Tipo de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domiciliación bancaria</fullName>
                <label>Domiciliació bancària</label>
            </value>
            <value>
                <fullName>Efectivo</fullName>
                <label>Efectiu</label>
            </value>
            <value>
                <fullName>Tarjeta</fullName>
                <label>Targeta</label>
            </value>
            <value>
                <fullName>Transferencia</fullName>
                <label>Transferència</label>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Vencimiento__c</fullName>
    <inlineHelpText>Nº de días al vencimiento de la factura.</inlineHelpText>
    <label>Vencimiento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/Vencimiento__c.object-meta.xml
<CustomObject>
    <label>Línea de Vencimiento</label>
    <nameField>
        <displayFormat>L.Venc# {0000000000}</displayFormat>
        <label>Vencimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Vencimiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vencimiento__c/fields/BIC_SWIFT__c.field-meta.xml
<CustomField>
    <fullName>BIC_SWIFT__c</fullName>
    <label>BIC/SWIFT</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factura</label>
    <referenceTo>Factura__c</referenceTo>
    <relationshipName>Vencimiento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Fecha_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_pago__c</fullName>
    <label>Fecha de pago</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Fecha_firma_mandato__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_mandato__c</fullName>
    <inlineHelpText>Data signatura mandat</inlineHelpText>
    <label>Fecha firma mandato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Fin_de_Facturaci_n__c.field-meta.xml
<CustomField>
    <fullName>Fin_de_Facturaci_n__c</fullName>
    <label>Fecha emisión</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Importe_de_factura__c.field-meta.xml
<CustomField>
    <fullName>Importe_de_factura__c</fullName>
    <label>Importe de factura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Importe_Total__c.field-meta.xml
<CustomField>
    <fullName>Importe_Total__c</fullName>
    <label>Importe Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Inicio_de_Facturaci_n__c.field-meta.xml
<CustomField>
    <fullName>Inicio_de_Facturaci_n__c</fullName>
    <label>Fecha Vencimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/N_mero_de_Factura__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_Factura__c</fullName>
    <label>Número de Factura</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/N_mero_de_pago__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pago__c</fullName>
    <label>Número de pago</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Nombre_de_la_factura__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_la_factura__c</fullName>
    <label>Nombre de la factura</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Referencia_mandato__c.field-meta.xml
<CustomField>
    <fullName>Referencia_mandato__c</fullName>
    <label>Referencia mandato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Referencia_recibo__c.field-meta.xml
<CustomField>
    <fullName>Referencia_recibo__c</fullName>
    <label>Referencia recibo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Residente__c.field-meta.xml
<CustomField>
    <fullName>Residente__c</fullName>
    <label>Residente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Tipo_adeudo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_adeudo__c</fullName>
    <inlineHelpText>FRST - FIRST
RCUR - RECURRENTE
FNAL - FINAL
OOFF - ÚNICO</inlineHelpText>
    <label>Tipo adeudo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FRST</fullName>
            </value>
            <value>
                <fullName>RCUR</fullName>
                <default>true</default>
                <label>RCUR</label>
            </value>
            <value>
                <fullName>FNAL</fullName>
            </value>
            <value>
                <fullName>OOFF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Tipo_de_factura__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_factura__c</fullName>
    <label>Tipo de factura</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/fields/Tipo_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pago__c</fullName>
    <label>Tipo de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domiciliación bancaria</fullName>
                <label>Domiciliació bancària</label>
            </value>
            <value>
                <fullName>Efectivo</fullName>
                <label>Efectiu</label>
            </value>
            <value>
                <fullName>Tarjeta</fullName>
                <label>Targeta</label>
            </value>
            <value>
                <fullName>Transferencia</fullName>
                <label>Transferència</label>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VencimientoController.cls
global class VencimientoController{
    
    @AuraEnabled
    webservice static String createVencimientos (String FactId, Integer numCuotas){
        system.debug('numCuotas'+ numCuotas);
        system.debug('FactID' + FactId );
        Set<Id> CuentasConFacturas = new Set<Id>();
        Set<Id> vencimientoPedido = new Set<Id>();
        Integer nf = numCuotas;
        
        //Esta es la Query que busca la info de la factura a la que se asociaran los vencimientos.
        Factura__c Fact1 = [SELECT ID, N_mero_de_factura__c, Name, Tipo__c, Importe_total_factura__c, Fecha_emisi_n_factura__c, Fin_periodo_facturaci_n__c, 
                            Tipo_de_pago__c, Tipo_de_Factura__c, Fecha_de_pago__c, Cliente__r.Id_Cliente__c, Cliente__r.Fecha_alta_original__c,
                            Cliente__r.CreatedDate, Cliente__c, Cliente__r.IBAN__c, Cliente__r.BIC_SWIFT__c, Cliente__r.Tipo_cuenta__c, Cliente__r.Categor_a__c,
                            Id_de_Pedido__c, Id_de_Oportunidad__c
                            FROM Factura__c 
                            WHERE Id =: FactId];
        
        //Esta es la Query que comprueba si esa factura tiene vencimientos anteriores.
        List<Vencimiento__c> registroVencimientos = [SELECT Id, Name 
                                                     FROM Vencimiento__c 
                                                     WHERE Factura__c =: FactId]; 
        
        //Se deletean los vencimientos anteriores para recalcular nuevos vencimientos automaticamente.
        database.delete(registroVencimientos);
        
        //Se crea una lista para almacenar los vencimientos y que no pete SF.
        List<Vencimiento__c> listaVencimientos = new List<Vencimiento__c>();
        
       
        //Buscamos si el cliente tiene más facturas domiciliadas
     	Integer facturasDom = [Select COUNT() From Factura__c Where Tipo_de_pago__c = 'Domiciliación bancaria' And Cliente__c = : Fact1.Cliente__c];
        System.debug('facturasDom :: ' + facturasDom); 
        System.debug('Fact1.Tipo_de_pago__c :: ' + Fact1.Tipo_de_pago__c);
        
        if ((Fact1.Tipo_de_pago__c == 'Domiciliación bancaria' && facturasDom > 1) || (Fact1.Tipo_de_pago__c != 'Domiciliación bancaria' && facturasDom > 0)){
            CuentasConFacturas.add(Fact1.Cliente__c);
        }
        
        //System.debug('CuentasConFacturas '+CuentasConFacturas);

        
        for (integer i=0; i< nf; i++){
            Integer numPago = i + 1;
            Vencimiento__c Venc1 = new Vencimiento__c ();    
            Venc1.Factura__c= FactId; 
            Venc1.N_mero_de_Factura__c= Fact1.N_mero_de_factura__c;
            Venc1.N_mero_de_pago__c=  (nf == 1)? 0: numPago;
            Venc1.Nombre_de_la_factura__c= Fact1.Name;
            Venc1.Tipo_de_Factura__c= Fact1.Tipo_de_Factura__c;
            Venc1.Importe_de_factura__c = Fact1.Importe_total_factura__c;
            Venc1.Importe_Total__c= Fact1.Importe_total_factura__c / numCuotas;
            Venc1.Inicio_de_Facturaci_n__c= Fact1.Fecha_emisi_n_factura__c;
            if (nf<=1 && (Fact1.Tipo_de_pago__c == 'Tarjeta' || Fact1.Tipo_de_pago__c == 'Web')){
                Venc1.Fecha_de_pago__c= Fact1.Fecha_de_pago__c;
            } else if (i > 0){
                date FechaVenc = Fact1.Fecha_emisi_n_factura__c;
                date FechaProxVenc = FechaVenc.toStartOfMonth();
                Integer NumMeses = 12/nf;
                Integer NC = NumMeses * i;
                Venc1.Inicio_de_Facturaci_n__c= FechaProxVenc.addMonths(NC) ;
            }
            Venc1.Fin_de_Facturaci_n__c= (Fact1.Tipo_de_pago__c == 'Tarjeta' || Fact1.Tipo_de_pago__c == 'Web')? Fact1.Fecha_emisi_n_factura__c : Venc1.Inicio_de_Facturaci_n__c;	
            Venc1.Tipo_de_Pago__c= Fact1.Tipo_de_pago__c;
            
            if (Fact1.Tipo_de_Pago__c == 'Domiciliación bancaria') {
                Venc1.BIC_SWIFT__c = Fact1.Cliente__r.BIC_SWIFT__c;
                Venc1.Referencia_recibo__c = Fact1.N_mero_de_factura__c + '/' + Venc1.N_mero_de_pago__c;
                
                String iban = Fact1.Cliente__r.IBAN__c;
                String ibanFormateado = Fact1.Cliente__r.IBAN__c;
                if (iban != null) {
                    iban = iban.replaceAll(' ', '');
                    if (iban.length() == 24) {
                        ibanFormateado = iban.substring(0, 4) + ' ' + iban.substring(4, 8) + ' ' + iban.substring(8, 12) + ' ' + iban.substring(12, 16) + ' ' + 
                            iban.substring(16, 20) + ' ' + iban.substring(20, 24);
                    }
                    //Indicamos si es un residente o no
                    Venc1.Residente__c = (Fact1.Cliente__r.IBAN__c.containsIgnoreCase('ES') == true)? 'S':'N';
                }
                Venc1.IBAN__c = ibanFormateado;
                /*
                //La referencia del mandato es el Id del cliente con mínimo 8 dígitos, sino, se le añaden 0s hasta conseguirlos
                String idCliente = String.valueOf(Fact1.Cliente__r.Id_Cliente__c);
                String refMandato = idCliente;
                if (idCliente.length() < 8) {
                    Integer tam = idCliente.length();
                    for (Integer j = tam; j < 9; j++) {
                        refMandato = '0'+refMandato;
                    }
                }
                Venc1.Referencia_mandato__c = refMandato;
                */
                
                //Fecha firma mandato es la fecha de alta original o la fecha de creación de la cuenta de no socio
                if (Fact1.Cliente__r.Tipo_cuenta__c != 'Cuenta personal') {
                    Datetime fechaCreacion = Fact1.Cliente__r.CreatedDate;
                    Date fecha = Date.newInstance(fechaCreacion.year(), fechaCreacion.month(), fechaCreacion.day());
                    Venc1.Fecha_firma_mandato__c = fecha;
                } else if (Fact1.Cliente__r.Tipo_cuenta__c == 'Cuenta personal') {
                    if (Fact1.Cliente__r.Categor_a__c == 'No_soci' || Fact1.Cliente__r.Categor_a__c == 'Menor No soci' ) {
                        Datetime fechaCreacion = Fact1.Cliente__r.CreatedDate;
                        Date fecha = Date.newInstance(fechaCreacion.year(), fechaCreacion.month(), fechaCreacion.day());
                        Venc1.Fecha_firma_mandato__c = fecha;
                    } else {
                        Venc1.Fecha_firma_mandato__c = Fact1.Cliente__r.Fecha_alta_original__c;
                    }
                }
                
                //Si es la primera domiciliación del cliente, hay que ponerle Tipo adeudo FIRST
                if (CuentasConFacturas.size() > 0) {
                    //System.debug('CuentasConFacturas tam '+CuentasConFacturas);
                    Boolean tieneFacturas = false;
                    //Si el cliente está en CuentasConFacturas, es que ya tiene y por tanto se mantiene el Tipo adeudo por defecto que es RCUR
                    for (Id idCuenta : CuentasConFacturas) {
                        if (idCuenta == Fact1.Cliente__c) {
                            tieneFacturas = true;
                        }
                    }
                    //System.debug('tieneFacturas '+tieneFacturas);
                }
                else { //Como no tiene facturas, le ponemos FRST
                    if (vencimientoPedido.size() < 1) {
                        System.debug('No vencimientos, no facturas');
                        Venc1.Tipo_adeudo__c = 'FRST';
                        if (Fact1.Id_de_Pedido__c != null) {
                            vencimientoPedido.add(Fact1.Id_de_Pedido__c);
                        }
                        if (Fact1.Id_de_Oportunidad__c != null) {
                            vencimientoPedido.add(Fact1.Id_de_Oportunidad__c);
                        }
                    }
                }
                
            } else {
                Venc1.Tipo_adeudo__c = null;
            }
            System.debug('vencimientoNuevo '+Venc1);
            
            listaVencimientos.add(Venc1);  
                
            }
            
            if(listaVencimientos.size() > 0){
                insert listaVencimientos;
                system.debug('listaVencimientos' + listaVencimientos);
            }        
            return ('Se han creado ' + nf + ' cuotas!');
        }
    }