force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Cobrada__c.field-meta.xml
<CustomField>
    <fullName>Cobrada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cobrada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_emisi_n_factura__c.field-meta.xml
<CustomField>
    <fullName>Fecha_emisi_n_factura__c</fullName>
    <label>Fecha emisión factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vencimiento__c</fullName>
    <label>Fecha vencimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <inlineHelpText>Iban del CEC para las transferencias</inlineHelpText>
    <label>IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Impagada__c.field-meta.xml
<CustomField>
    <fullName>Impagada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Impagada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Importe_total_factura__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_factura__c</fullName>
    <label>Importe total factura</label>
    <summarizedField>L_neas_de_factura__c.Importe__c</summarizedField>
    <summaryForeignKey>L_neas_de_factura__c.Factura__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Inicio_periodo_facturaci_n__c.field-meta.xml
<CustomField>
    <fullName>Inicio_periodo_facturaci_n__c</fullName>
    <label>Inicio periodo facturación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/N_mero_de_factura__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_factura__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <label>Número de factura</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Periodo_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Periodo_de_pago__c</fullName>
    <label>Periodo de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_Factura__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Factura__c</fullName>
    <label>Tipo de Factura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Definitiva</fullName>
            </value>
            <value>
                <fullName>Rectificativa</fullName>
            </value>
            <value>
                <fullName>Proforma</fullName>
                <isActive>false</isActive>
                <label>Proforma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pago__c</fullName>
    <label>Tipo de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domiciliación bancaria</fullName>
                <label>Domiciliació bancària</label>
            </value>
            <value>
                <fullName>Efectivo</fullName>
                <label>Efectiu</label>
            </value>
            <value>
                <fullName>Tarjeta</fullName>
                <label>Targeta</label>
            </value>
            <value>
                <fullName>Transferencia</fullName>
                <label>Transferència</label>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/productSuscriptionList.cls
global class productSuscriptionList {
   
    public static Map<String, Product2> getProductoModalidad() {
        Map<String, Product2> productoModalidad = new Map<String, Product2>();
		List<String> listaModalidades = getListaModalidades();
        List<Product2> productosSuscripcion = productSuscriptionList();
        
        //System.debug('Mapa modalidad - producto');
        for (String modalidad : listaModalidades) {
            for (Product2 producto : productosSuscripcion) {
                if (producto.Modalidad_a_asignar__c == modalidad) {
                    //System.debug('Modalidad: '+modalidad+'; Producto: '+producto.Id);
                    productoModalidad.put(modalidad, producto);
                } else if (producto.Role_to_assign__c == 'soci_participatiu' && producto.Role_to_assign__c == modalidad) {
                    //System.debug('Modalidad: '+modalidad+'; Producto: '+producto.Id);
                    productoModalidad.put(modalidad, producto); 
                }
            }
        }
        return productoModalidad;
    }
    
     public static List<Product2> productSuscriptionList() {
        List<Product2> productosSuscripcion = [Select Id, Name, Role_to_assign__c, Modalidad_a_asignar__c,tax_status__c,tax_class__c, 
                                               (Select UnitPrice, Pricebook2.Name From PricebookEntries Where Pricebook2.Name != 'Standard Price Book')
                                               From Product2 Where Product_type__c = 'subscription' and Role_to_assign__c != null And isActive = true];
        return productosSuscripcion;
    }
    
    public static List<String> getListaModalidades(){
        List<String> listaModalidades= new List<String>();
        Schema.DescribeFieldResult fieldResult = Account.Modalidad__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            listaModalidades.add(pickListVal.getValue());
        }
        listaModalidades.add('soci_participatiu');
        return listaModalidades;
    }
    
    public static List<Factura__c> getFacturasCreadas(Set<Id> SetIdFacturas) {
        List<Factura__c> facturasCreadas = [Select Id, Name, N_mero_de_factura__c, Tipo_de_pago__c, Tipo_de_Factura__c, Inicio_periodo_facturaci_n__c, Importe_total_factura__c, Cobrada__c, Impagada__c, 
                                            Fecha_vencimiento__c, Fecha_de_pago__c, Fecha_emisi_n_factura__c, Periodo_de_pago__c, Cliente__r.Id_Cliente__c, Cliente__r.Fecha_alta_original__c,
                                            Cliente__r.CreatedDate, Cliente__c, Cliente__r.IBAN__c, Cliente__r.BIC_SWIFT__c
                                            From Factura__c Where Id =: SetIdFacturas And Periodo_de_pago__c != null];
        return facturasCreadas;
    }
    
    public static Product2 getSuplemento() {
        Product2 productosSuplemento = [Select Id, Name, Role_to_assign__c, Modalidad_a_asignar__c,tax_status__c,tax_class__c, 
                                               (Select UnitPrice, Pricebook2.Name From PricebookEntries Where Pricebook2.Name != 'Standard Price Book')
                                               From Product2 Where Product_type__c = 'subscription' and Name = 'Suplemento' And isActive = true];
        return productosSuplemento;
    }
    
    public static List<Factura__c> getCuentasConFacturasDomiciliadas(Set<Id> SetIdCuentas) {
        List<Factura__c> facturas = [Select Id, Cliente__c From Factura__c Where Tipo_de_pago__c = 'Domiciliación bancaria' And Cliente__c = : SetIdCuentas];
        return facturas;
    }
    
    public static Product2 getRevista(String nombreRevista) {
        Product2 productoRevista = [Select Id, Name, Role_to_assign__c, Modalidad_a_asignar__c,tax_status__c,tax_class__c, 
                                               (Select UnitPrice, Pricebook2.Name From PricebookEntries Where Pricebook2.Name = 'Standard Price Book')
                                               From Product2 Where Product_type__c = 'subscription' and Name =:nombreRevista  And isActive = true];
        return productoRevista;
    }
}