force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_emisi_n_factura__c.field-meta.xml
<CustomField>
    <fullName>Fecha_emisi_n_factura__c</fullName>
    <label>Fecha emisión factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Id_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Id_de_Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_Factura__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Factura__c</fullName>
    <label>Tipo de Factura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Definitiva</fullName>
            </value>
            <value>
                <fullName>Rectificativa</fullName>
            </value>
            <value>
                <fullName>Proforma</fullName>
                <isActive>false</isActive>
                <label>Proforma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pago__c</fullName>
    <label>Tipo de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domiciliación bancaria</fullName>
                <label>Domiciliació bancària</label>
            </value>
            <value>
                <fullName>Efectivo</fullName>
                <label>Efectiu</label>
            </value>
            <value>
                <fullName>Tarjeta</fullName>
                <label>Targeta</label>
            </value>
            <value>
                <fullName>Transferencia</fullName>
                <label>Transferència</label>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExtensionFacturaPDF_Test.cls
/*
*   @clase : ExtensionFacturaPDF_Test
*
*   @Author             :   Eduardo Homez <eduardo.homez@birchmangroup.com>
*   @Created            :   13 Nov 2018
*   @Description        :   test
*
*   Modification Log
*   ----------------------------------------------------------------------------------------------------------------------------
*   #       Developer               Date                    Description
*   ----------------------------------------------------------------------------------------------------------------------------
*   1       Eduardo Homez         	13 Nov 2018             Creation @istest
*   2       Melanie Caballero       13 Nov 2018             Modification
*
*/

@isTest
public class ExtensionFacturaPDF_Test {
    @testSetup 
    public static void setup() {
        TestObjects.initializeObjects();
    }
    
    @isTest
    public static void case1(){
        
        Account acc = new Account();
        acc.LastName = 'Lastname Acc Test';
        acc.Categor_a__c = 'Ple_dret';
        acc.Modalidad__c = 'Familiar';
        acc.PersonEmail = 'Test@test.com';
        acc.Tipo_de_documento__c = 'dni';
        acc.N_mero_de_Documento__pc = '79785079F';
        database.insert(acc);
        
        
        Order ord = new Order();
        ord.accountid = acc.id;
        ord.EffectiveDate = Date.today();
        ord.Status = 'Borrador';
        ord.Pricebook2Id = Test.getStandardPricebookId();
        database.insert(ord);
    
        
        Factura__c factura = new Factura__c ();
        factura.Name = 'Pedido '+ ord.OrderNumber;
        factura.Cliente__c = ord.AccountId;
        factura.Fecha_emisi_n_factura__c = Date.today();
        factura.Tipo_de_pago__c = ord.Tipo_de_pago__c;
        factura.Tipo_de_Factura__c='Definitiva';
        factura.Id_de_Pedido__c= ord.id;
        database.insert(factura);
        
    }
    
    @isTest
    public static void case2(){
        Account acc = TestObjects.createPersonalAccount();
        acc.Tipo_de_documento__c = 'dni';
        acc.N_mero_de_Documento__pc = '79785079F';
            database.insert(acc);
        Order ord = TestObjects.createOrder(acc);
        	database.insert(ord);
        Product2 pro = TestObjects.createProduct();
        	database.insert(pro);
        PriceBookEntry pbe = TestObjects.createPriceBookEntry(pro);
        	database.insert(pbe);
        OrderItem oi = TestObjects.createOrderItem(ord, pbe, pro);
        	database.insert(oi);
        Factura__c factura = TestObjects.createFacturaOrder(ord);
        	database.insert(factura);
        
        ApexPages.StandardController stdCtr = new apexPages.StandardController(factura);
		ExtensionFacturaPDF ef = new ExtensionFacturaPDF(stdCtr);
       //ExtensionFacturaPDF.ExtensionFacturaPDF(ApexPages.ctr)
       
    }

}