force-app/main/default/objects/Alquiler_Material__c/Alquiler_Material__c.object-meta.xml
<CustomObject>
    <label>Alquiler Material</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Número alquiler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alquiler Material</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alquiler_Material__c/fields/devuelto__c.field-meta.xml
<CustomField>
    <fullName>devuelto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Devuelto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Alquiler_Material__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <description>Fecha limite para la devolución del material.</description>
    <label>Fecha fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EmailMaterial_Test.cls
/*
*   @clase : EmailMaterial_Test
*
*   @Author             :   Juan Jose Sáez Martinez <juanjose.saez@birchmangroup.com>
*   @Created            :   19/ Sep 2018
*   @Description        :   Test de Clase que automatiza el envio de email a clientes que tienen material alquilado y les recuerda que tienen que devolverlo
*
*   Modification Log
*   ----------------------------------------------------------------------------------------------------------------------------
*   #       Developer               Date                    Description
*   ----------------------------------------------------------------------------------------------------------------------------    
*   1  Juan Jose Sáez Martinez     19 Sep 2018                 Clase Test
*			
*   
*/
@isTest
public class EmailMaterial_Test {
    @testSetup 
    public static void setup() {
        TestObjects.initializeObjects();
    }
    
			@isTest
    public static void Test1() {
        
        Alquiler_Material__c am = TestObjects.createAlquilerMaterial(); 
        am.Fecha_Fin__c = date.today()+1;
        am.devuelto__c = false;
        insert am;
        
        
        
        System.debug('fecha fin: '+am.Fecha_Fin__c);
        
        Test.startTest();
        EmailMaterial EmailM = new EmailMaterial();
        database.executeBatch(EmailM,50);
        Test.stopTest();
        }
    public static void Test2() {
        
					       
        }
}