force-app/main/default/objects/Alquiler_Material__c/Alquiler_Material__c.object-meta.xml
<CustomObject>
    <label>Alquiler Material</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Número alquiler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alquiler Material</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empleados__c/Empleados__c.object-meta.xml
<CustomObject>
    <label>Empleado</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empleados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Etapas_socio__c/Etapas_socio__c.object-meta.xml
<CustomObject>
    <label>Etapas socio</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Etapas socio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Etapas socio</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Vencimiento__c</fullName>
    <inlineHelpText>Nº de días al vencimiento de la factura.</inlineHelpText>
    <label>Vencimiento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/L_neas_de_factura__c/L_neas_de_factura__c.object-meta.xml
<CustomObject>
    <label>Líneas de factura</label>
    <nameField>
        <displayFormat>LF-{0000}</displayFormat>
        <label>Nombre de Líneas de factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de factura</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/L_neas_de_factura__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <label>Factura</label>
    <referenceTo>Factura__c</referenceTo>
    <relationshipLabel>Líneas de factura</relationshipLabel>
    <relationshipName>L_neas_de_factura</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vencimiento__c/Vencimiento__c.object-meta.xml
<CustomObject>
    <label>Línea de Vencimiento</label>
    <nameField>
        <displayFormat>L.Venc# {0000000000}</displayFormat>
        <label>Vencimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Vencimiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vencimiento__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factura</label>
    <referenceTo>Factura__c</referenceTo>
    <relationshipName>Vencimiento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestObjects_Test.cls
@isTest
public class TestObjects_Test {
    /*
	
    @isTest
    public static void case1() {
        RecordType rt = [SELECT id FROM RecordType WHERE SObjectType=:'Account' AND Name =: 'Cuenta empresa' LIMIT 1];
        System.debug(rt);
        
        Account acc1 = TestObjects.createEmpresaAccount(rt);
        acc1.N_de_socio__c = 1223.0;
        database.insert (acc1);
        
        Account acc2 = TestObjects.createPersonalAccount();
        acc2.N_de_socio__c = 1231.0;
        database.insert (acc2);
        
        Contact con = TestObjects.createContact();
        database.insert (con);
        
        Opportunity opp = TestObjects.createOpportunity();
        database.insert (opp);
        
        Product2 pro = TestObjects.createProduct();
        database.insert (pro);
        
        Etapas_socio__c etapa = TestObjects.createEtapasSocio(acc1);
        database.insert (etapa);
        
        Empleados__c emp = TestObjects.createEmpleados();
        database.insert (emp);
        
        PriceBook2 pb = new PriceBook2(id=Test.getStandardPricebookId());
        
        Order ord = TestObjects.createOrder(acc2);
        ord.Pricebook2Id = pb.id;
        database.insert (ord);
        
        PriceBookEntry pbe = TestObjects.createPriceBookEntry(pro);
        pbe.Pricebook2Id = pb.id;
        database.insert (pbe);
        
        OrderItem oItem = TestObjects.createOrderItem(ord, pbe, pro);
        database.insert (oItem);
        
        Alquiler_Material__c am = TestObjects.createAlquilerMaterial();
        database.insert(am);
        
        Factura__c factura = TestObjects.createFacturaOrder(ord);
        database.insert(factura);
        
        L_neas_de_factura__c linFac = TestObjects.createLineasFacturaOrder(factura, oItem);
        database.insert(linFac);
        
        Vencimiento__c vencimiento = TestObjects.createVencimientos(factura);
        database.insert(vencimiento);
        
        OpportunityLineItem oppItem = TestObjects.createOpportunityItem(opp, pbe, pro);
        database.insert(oppItem);
        
        Factura__c facturaOpp = TestObjects.createFacturaOpportunity(opp);
        database.insert(facturaOpp);
        
        L_neas_de_factura__c linFacOpp = TestObjects.createLineasFacturaOpportunity(facturaOpp, oppItem);
        database.insert(linFacOpp);
    }*/
}